import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';
import Navbar from '../components/Navbar';

export default function Dashboard() {
  const { user } = useAuth();
  const [invoices, setInvoices] = useState([]);
  const [employees, setEmployees] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const load = async () => {
      try {
        const invRes = await api.get('/invoices');
        setInvoices(invRes.data.invoices);
        if (user?.role === 'admin') {
          const empRes = await api.get('/employees');
          setEmployees(empRes.data.employees);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [user]);

  const totalRevenue = invoices.reduce((sum, inv) => sum + Number(inv.grand_total), 0);
  const thisMonth = invoices.filter((inv) => {
    const d = new Date(inv.invoice_date);
    const now = new Date();
    return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
  });

  const StatCard = ({ label, value, accent }) => (
    <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-5">
      <div className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2">{label}</div>
      <div className={`text-2xl font-extrabold ${accent || 'text-navy'}`}>{value}</div>
    </div>
  );

  return (
    <div className="min-h-screen bg-gray-100">
      <Navbar />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-2xl font-bold text-navy">Dashboard</h1>
            <p className="text-sm text-gray-500">Overview of your billing activity</p>
          </div>
          <Link to="/invoices/new" className="bg-gold hover:brightness-95 transition text-navy font-bold text-sm px-5 py-2.5 rounded-lg shadow">
            + Create Invoice
          </Link>
        </div>

        <div className={`grid grid-cols-1 sm:grid-cols-2 ${user?.role === 'admin' ? 'lg:grid-cols-4' : 'lg:grid-cols-3'} gap-4 mb-8`}>
          <StatCard label="Total Invoices" value={invoices.length} />
          <StatCard label="Invoices This Month" value={thisMonth.length} />
          <StatCard label="Total Billed Amount" value={`₹${totalRevenue.toLocaleString('en-IN', { maximumFractionDigits: 0 })}`} accent="text-green-600" />
          {user?.role === 'admin' && <StatCard label="Active Employees" value={employees.filter((e) => e.status === 'active').length} accent="text-blue-600" />}
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
            <h2 className="font-bold text-navy">Recent Invoices</h2>
            <Link to="/invoices" className="text-sm text-navy font-semibold hover:underline">View all</Link>
          </div>
          {loading ? (
            <div className="p-6 text-sm text-gray-500">Loading...</div>
          ) : invoices.length === 0 ? (
            <div className="p-6 text-sm text-gray-500">No invoices yet. Create your first invoice to get started.</div>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-gray-500 uppercase text-xs">
                  <th className="text-left px-5 py-3">Invoice #</th>
                  <th className="text-left px-5 py-3">Client</th>
                  <th className="text-left px-5 py-3">Date</th>
                  <th className="text-right px-5 py-3">Amount</th>
                  <th className="text-left px-5 py-3">Generated By</th>
                  <th className="px-5 py-3"></th>
                </tr>
              </thead>
              <tbody>
                {invoices.slice(0, 6).map((inv) => (
                  <tr key={inv.id} className="border-t border-gray-100 hover:bg-gray-50">
                    <td className="px-5 py-3 font-semibold text-navy">{inv.invoice_number}</td>
                    <td className="px-5 py-3">{inv.client_name}</td>
                    <td className="px-5 py-3">{new Date(inv.invoice_date).toLocaleDateString('en-IN')}</td>
                    <td className="px-5 py-3 text-right font-semibold">₹{Number(inv.grand_total).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>
                    <td className="px-5 py-3">{inv.generated_by_name}</td>
                    <td className="px-5 py-3 text-right">
                      <Link to={`/invoices/${inv.id}`} className="text-navy font-semibold hover:underline">View</Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}
