import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import toast from 'react-hot-toast';
import api from '../api/axios';
import Navbar from '../components/Navbar';
import { useAuth } from '../context/AuthContext';

export default function Invoices() {
  const { user } = useAuth();
  const isAdmin = user?.role === 'admin';
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  const [deletingId, setDeletingId] = useState(null);

  useEffect(() => {
    api.get('/invoices').then((res) => setInvoices(res.data.invoices)).finally(() => setLoading(false));
  }, []);

  const handleDelete = async (inv) => {
    if (!window.confirm(`Delete invoice ${inv.invoice_number}? This cannot be undone.`)) return;
    setDeletingId(inv.id);
    try {
      await api.delete(`/invoices/${inv.id}`);
      setInvoices((prev) => prev.filter((i) => i.id !== inv.id));
      toast.success(`Invoice ${inv.invoice_number} deleted.`);
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to delete invoice.');
    } finally {
      setDeletingId(null);
    }
  };

  const filtered = invoices.filter((inv) =>
    inv.invoice_number.toLowerCase().includes(search.toLowerCase()) ||
    inv.client_name.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-gray-100">
      <Navbar />
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
          <div>
            <h1 className="text-2xl font-bold text-navy">Invoices</h1>
            <p className="text-sm text-gray-500">All invoices you have access to</p>
          </div>
          <div className="flex gap-3">
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by invoice # or client..."
              className="border border-gray-300 rounded-lg px-4 py-2 text-sm w-64 focus:ring-2 focus:ring-navy/30"
            />
            <Link to="/invoices/new" className="bg-navy hover:bg-navy-dark transition text-white font-semibold text-sm px-5 py-2.5 rounded-lg shadow">
              + New Invoice
            </Link>
          </div>
        </div>

        <div className="bg-white rounded-xl shadow-sm border border-gray-100 overflow-hidden">
          {loading ? (
            <div className="p-6 text-sm text-gray-500">Loading...</div>
          ) : filtered.length === 0 ? (
            <div className="p-6 text-sm text-gray-500">No invoices found.</div>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-gray-50 text-gray-500 uppercase text-xs">
                  <th className="text-left px-5 py-3">Invoice #</th>
                  <th className="text-left px-5 py-3">Type</th>
                  <th className="text-left px-5 py-3">Client</th>
                  <th className="text-left px-5 py-3">Date</th>
                  <th className="text-right px-5 py-3">Amount</th>
                  <th className="text-left px-5 py-3">Generated By</th>
                  <th className="px-5 py-3"></th>
                </tr>
              </thead>
              <tbody>
                {filtered.map((inv) => (
                  <tr key={inv.id} className="border-t border-gray-100 hover:bg-gray-50">
                    <td className="px-5 py-3 font-semibold text-navy">{inv.invoice_number}</td>
                    <td className="px-5 py-3 capitalize">
                      <span className={`px-2.5 py-1 rounded-full text-xs font-semibold ${inv.invoice_type === 'tax' ? 'bg-purple-100 text-purple-700' : inv.invoice_type === 'simple' ? 'bg-green-100 text-green-700' : 'bg-blue-100 text-blue-700'}`}>
                        {inv.invoice_type}
                      </span>
                    </td>
                    <td className="px-5 py-3">{inv.client_name}</td>
                    <td className="px-5 py-3">{new Date(inv.invoice_date).toLocaleDateString('en-IN')}</td>
                    <td className="px-5 py-3 text-right font-semibold">₹{Number(inv.grand_total).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td>
                    <td className="px-5 py-3">{inv.generated_by_name}</td>
                    <td className="px-5 py-3 text-right whitespace-nowrap">
                      <Link to={`/invoices/${inv.id}`} className="text-navy font-semibold hover:underline">View</Link>
                      {isAdmin && (
                        <button
                          type="button"
                          onClick={() => handleDelete(inv)}
                          disabled={deletingId === inv.id}
                          className="text-red-500 font-semibold hover:underline ml-4 disabled:opacity-50"
                        >
                          {deletingId === inv.id ? 'Deleting...' : 'Delete'}
                        </button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}
